version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/go-playground/validator/v10
    versions:
    - 10.4.2
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/google/uuid
    versions:
    - 1.2.0
